import Head from "next/head";
import { checkout } from "../checkout";

export default function Home() {
  return (
    <>
      <Head>
        <title>Payments App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <button
        onClick={() => {
          checkout({
            lineItems: [
              {
                price: "price_1MtWYoCs2iAodiD7edm8y99m",
                quantity: 1,
              },
            ],
          });
        }}
      >
        BUY!
      </button>
    </>
  );
}
